easy_admin:
  formats:
    datetime: 'd/m/Y h:i'
  site_name: 'Administration Freeworld'
  design:
    brand_color: 'orange'
    form_theme: 'vertical'
  entities:

    User:
      class: App\Entity\Person
      label: Utilisateurs
      list:
        fields:
        - 'id'
        - { property: 'username', label: "Nom d'utilisateur" }
        - { property: 'role',  type: 'raw' }
        - { property: 'email', label: "Email" }
        - { property: 'city', label: "Ville" }
        - { property: 'description', label: "Description" }
        - { property: 'isactive',  type: 'toggle' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit User'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'username', label: "Nom d'utilisateur" }
        - { property: 'role',  type: 'raw' }
      show:
        fields:
        - 'id'
        - { property: 'username', label: "Nom d'utilisateur" }
        - { property: 'role',  type: 'raw' }
        - { property: 'email', label: "Email" }
        - { property: 'city', label: "Ville" }
        - { property: 'description', label: "Description" }
        - { property: 'isactive',  type: 'toggle' }


    Place:
      class: App\Entity\Place
      label: Lieux référencés
      list:
        fields:
        - 'id'
        - { property: 'name',  label: 'Nom' }
        - { property: 'address',  label: 'Adresse' }
        - { property: 'description',  label: 'Description' }
        - { property: 'image',  label: 'Illustration' }
        - { property: 'positiveOpinion',  label: 'Réactions positives' }
        - { property: 'negativeOpinion',  label: 'Réactions négatives' }
        - { property: 'city_id.real_name',  label: 'Ville' }
        - { property: 'user_id.username',  label: 'Créateur du lieu' }
        - { property: 'longitudeDeg',  label: 'Longitude' }
        - { property: 'latitudeDeg',  label: 'Latitude' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Place'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'name',  label: 'Nom' }
        - { property: 'address',  label: 'Adresse' }
        - { property: 'description',  label: 'Description' }
        - { property: 'image',  label: 'Illustration' }
#        - 'city_id'
        - { property: 'user_id',  label: 'Créateur du lieu' }
        - { property: 'longitudeDeg',  label: 'Longitude' }
        - { property: 'latitudeDeg',  label: 'Latitude' }
      show:
        fields:
        - { property: 'name',  label: 'Nom' }
        - { property: 'address',  label: 'Adresse' }
        - { property: 'description',  label: 'Description' }
        - { property: 'image',  label: 'Illustration' }
        - { property: 'city_id.real_name',  label: 'Ville' }
        - { property: 'user_id',  label: 'Créateur du lieu' }
        - { property: 'longitudeDeg',  label: 'Longitude' }
        - { property: 'latitudeDeg',  label: 'Latitude' }


    City:
      class: App\Entity\City
      disabled_actions: ['edit', 'delete']
      label: Villes couvertes
      list:
        fields:
        - 'id'
        - { property: 'realName',  label: 'Nom' }
        - { property: 'postalCode',  label: 'Code postal' }
        - { property: 'country_id',  label: 'Pays' }
        - { property: 'longitudeDeg',  label: 'Longitude' }
        - { property: 'latitudeDeg',  label: 'Latitude' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
      show:
        fields:
        - 'id'
        - { property: 'realName',  label: 'Nom' }
        - { property: 'postalCode',  label: 'Code postal' }
        - { property: 'country_id',  label: 'Pays' }
        - { property: 'longitudeDeg',  label: 'Longitude' }
        - { property: 'latitudeDeg',  label: 'Latitude' }


    Event:
      class: App\Entity\Event
      label: Les évènements référencés
      list:
        fields:
        - 'id'
        - { property: 'name', label: "Nom de l'évènement" }
        - { property: 'coordonates', label: "Coordonnées de l'évènement" }
        - { property: 'description', label: "Description" }
        - { property: 'begin', label: "date de début" }
        - { property: 'end', label: "date de fin" }
        - { property: 'image', label: "Image d'illustration" }
        - { property: 'place_id.name', label: "Lieu" }
        - { property: 'user_id', label: "Créateur de l'évènement" }
        - { property: 'types', label: "Types d'évènement" }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Event'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'name', label: "Nom de l'évènement" }
        - { property: 'coordonates', label: "Coordonnées de l'évènement" }
        - { property: 'description', label: "Description" }
        - { property: 'begin', label: "date de début" }
        - { property: 'end', label: "date de fin" }
        - { property: 'image', label: "Image d'illustration" }
        - { property: 'place_id', label: "Lieu" }
        - { property: 'user_id', label: "Créateur de l'évènement" }
        - { property: 'types', label: "Types d'évènement" }
      show:
        fields:
        - { property: 'name', label: "Nom de l'évènement" }
        - { property: 'coordonates', label: "Coordonnées de l'évènement" }
        - { property: 'description', label: "Description" }
        - { property: 'begin', label: "date de début" }
        - { property: 'end', label: "date de fin" }
        - { property: 'image', label: "Image d'illustration" }
        - { property: 'place_id', label: "Lieu" }
        - { property: 'user_id', label: "Créateur de l'évènement" }
        - { property: 'types', label: "Types d'évènement" }


    Post:
      class: App\Entity\Post
      label: Les commentaires relatifs aux lieux
      list:
        fields:
        - 'id'
        - { property: 'title', label: "Titre du commentaire" }
        - { property: 'body', label: "Corps du commentaire" }
        - { property: 'vote', label: "Vote de l'auteur", type: 'text'}
        - { property: 'image', label: "Illustration/photo" }
        - { property: 'released_date', label: "date de création" , type: 'datetime' }
        - { property: 'positive_Opinion', label: "Nb de réactions positives" }
        - { property: 'negative_Opinion', label: "Nb de réactions négatives" }
        - { property: 'place', label: "Lieu en question" }
        - { property: 'author', label: "Auteur du commentaire" }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Post'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'title', label: "Titre du commentaire" }
        - { property: 'body', label: "Corps du commentaire" }
        - { property: 'image', label: "Illustration/photo" }
        - { property: 'released_date', label: "Date de création" , type: 'datetime' }
        - { property: 'place', label: "Lieu en question" }
        - { property: 'author', label: "Auteur du commentaire" }
      show:
        fields:
        - { property: 'title', label: "Titre du commentaire" }
        - { property: 'body', label: "Corps du commentaire" }
        - { property: 'image', label: "Illustration/photo" }
        - { property: 'released_date', label: "Date de création" , type: 'datetime' }
        - { property: 'positive_Opinion', label: "Nb de réactions positives" }
        - { property: 'negative_Opinion', label: "Nb de réactions négatives" }
        - { property: 'place', label: "Lieu en question" }
        - { property: 'author', label: "Auteur du commentaire" }


    Comment:
      class: App\Entity\Comment
      label: Les réactions aux commentaires
      list:
        fields:
        - 'id'
        - { property: 'body',  label: 'Commentaire' }
        - { property: 'releasedDate', label: "Date de création" , type: 'datetime' }
        - { property: 'user_id',  label: 'Auteur' }
        - { property: 'post_id',  label: 'En réponse à:' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Comment'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'body',  label: 'Commentaire' }
        - { property: 'releasedDate', label: "Date de création" , type: 'datetime' }
        - { property: 'user_id',  label: 'Auteur' }
        - { property: 'post_id',  label: 'En réponse à:' }
      show:
        fields:
        - 'id'
        - 'id'
        - { property: 'body',  label: 'Commentaire' }
        - { property: 'releasedDate', label: "date de création" , type: 'datetime' }
        - { property: 'user_id',  label: 'Auteur' }
        - { property: 'post_id',  label: 'En réponse à:' }


    Role:
      class: App\Entity\Role
      disabled_actions: ['delete', 'edit', 'show']
      label: liste des rôles des utilisateurs
      list:
        fields:
        - 'id'
        - { property: 'name',  label: 'Role' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Role'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'name',  label: 'Role' }


    Accessibility:
      class: App\Entity\Accessibility
      label: Les équipements d'accèssibilité
      list:
        fields:
        - 'id'
        - { property: 'equipment',  label: "Type d'équipement" }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Access Equipment'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'equipment',  label: "Type d'équipement" }
      show:
        fields:
        - 'id'
        - { property: 'equipment',  label: "Type d'équipement" }


#    PlaceType:
#      class: App\Entity\PlaceType
#      label: Associations Lieux - Types de lieu
#      list:
#        fields:
#        - 'id'
#        - 'type'
#        - 'places'
#        actions:
#        - { name: 'show', icon: 'info-circle', label: 'Show' }
#        - { name: 'edit', icon: 'pencil', label: 'Edit' }
#      form:
#        title: 'Add/Edit Placetype'
#        form_options: { validation_groups: ['Default'] }
#        fields:
#        - 'type'
#        - 'places'


    Type:
      class: App\Entity\Type
      label: Les types d'évènements
      list:
        fields:
        - 'id'
        - { property: 'name',  label: 'Type' }
        - { property: 'events',  label: 'Evènements de ce type' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Type of Event'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'name',  label: 'Type' }
        - { property: 'events',  label: 'Evènements de ce type' }
      show:
        fields:
        - { property: 'name',  label: 'Type' }
        - { property: 'events',  label: 'Evènements de ce type' }


    Country:
      class: App\Entity\Country
      disabled_actions: ['delete', 'edit', 'show']
      label: Les pays
      list:
        fields:
        - 'id'
        - { property: 'name',  label: 'Pays' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      form:
        title: 'Add/Edit Country'
        form_options: { validation_groups: ['Default'] }
        fields:
        - { property: 'name',  label: 'Pays' }

    Messages:
      class: App\Entity\Messages
      disabled_actions: ['delete']
      label: messages reçus
      list:
        fields:
        - 'id'
        - { property: 'title',  label: 'Titre' }
        - { property: 'message',  label: 'Message' }
        - { property: 'firstname',  label: "Prénom de l'auteur" }
        - { property: 'lastname',  label: "Nom de l'auteur" }
        - { property: 'email',  label: 'Email' }
        - { property: 'phone',  label: 'Téléphone' }
        - { property: 'is_treated',  type: 'toggle' }
        actions:
        - { name: 'show', icon: 'info-circle', label: 'Show' }
        - { name: 'edit', icon: 'pencil', label: 'Edit' }
      show:
        fields:
        - 'id'
        - { property: 'title',  label: 'Titre' }
        - { property: 'message',  label: 'Message' }
        - { property: 'firstname',  label: "Prénom de l'auteur" }
        - { property: 'lastname',  label: "Nom de l'auteur" }
        - { property: 'email',  label: 'Email' }
        - { property: 'phone',  label: 'Téléphone' }
        - { property: 'is_treated',  type: 'toggle' }

