lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'galaxy'
    token_ttl:   3600
#    // ATTENTION - PASSER LA PASSPHRASE EN VARIABLE POUR SECURITE
